version: '1'
services:
  couchdb:
    image: couchdb:latest
    ports:
      ['5984:5984']
    environment:
      COUCHDB_USER= admin
      COUCHDB_PASSWORD= password
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      ['3000:3000']
    depends_on:
      couchdb
frontend:
  build:
    context: ./front
    dockerfile: Dockerfile
  ports:
    ['5173:5173']
  depends_on:
    backend